@baseUrl = http://127.0.0.1:8000

### 1. 创建用户 (POST form-data)
POST {{baseUrl}}/form
Content-Type: multipart/form-data

{}


### 2. 测试
POST {{baseUrl}}/user
Content-Type: text/xml

<user>
    <name>张三</name>
    <age>20</age>
</user>
